### ISSUE TITLE
Code does not work when I deploy it in server

### ISSUE THREAD

**Issue by user1689** [Seung3837/Typescript-ReactJS-WebRTC-1-N-SFU#5]
Thanks your for sharing project. Your project is awesome. 

When I run both server and client locally, it works. But I got some issue when I deploy it in AWS EC2 instance t2.micro. I do not know why. I try a lot of methods to figure it out, stream was added correctly, until now I did not find a suitable way to fix it. 

Situation like when others join, in my window, others video is only black, no video shown.

**Comment by millo-L** [comment]
Thank you for your compliment.

If you want to run server not locally, you must set ssl/tls domain for streaming server.

**Comment by user1689** [comment]
Thanks for reaching out and advice. 

After troubleshooting, the problem is in the gathering ICE candidates.
